baseURL = "https://dompb.github.io/dompb"
languageCode = "en-us"
title = "Dominic Browne"

theme = "coder" # Set the theme.
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "Dominic Browne" # Author's name.
    info = "Full Stack Developer (C++, Python, JavaScript)" # Author's job title or info.
    description = "Dominic Brownes's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.

#    disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
	custom_css = []

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/dompb/"
#[[params.social]]
#    name = "Twitter"
#    weight = 2
#    url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/dominic-browne-32350b31/"

# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/posts/"
#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "/about/"
